### ISSUE TITLE
Is this in use?

### ISSUE THREAD

**Issue by furzeface** [techmatt101/Surveyorsaurus#1]
I want to play with it! :smile:

**Comment by techmatt101** [comment]
Yes please, be my guest! Started writing tests and a web app for viewing results but have been super lazy of late and really need to continue with the project.

**Comment by furzeface** [comment]
Needs to be published then! Publish it to npm and let me have a play then also I will try and contribute some tests :octocat: :octocat: :octocat:

**Comment by techmatt101** [comment]
I've published the module. Enjoy. 
https://www.npmjs.com/package/surveyorsaurus
